HW3 is completed
AndreyNagorskiy/otus-go-hw pull request #3
Opened 2024-12-24 16:06 UTC by AndreyNagorskiy

## Домашнее задание №3 «Частотный анализ»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-12-24 19:39 UTC, vladislavmass requested changes

2024-12-24 19:39 UTC, vladislavmass commented on hw03_frequency_analysis/top.go
> +	re := regexp.MustCompile(`^[^a-zA-Zа-яА-Я0-9]+|[^a-zA-Zа-яА-Я0-9]+$`)
Почему бы нам не вынести эту переменную на уровень пакета, тем самым скомпилировав регулярное выражение всего 1 раз, а не на каждое слово делать компиляцию

2024-12-24 19:39 UTC, vladislavmass commented on hw03_frequency_analysis/top.go
> +	return regexp.MustCompile(`^-+$`).MatchString(s)
Почему бы нам не вынести эту переменную на уровень пакета, тем самым скомпилировав регулярное выражение всего 1 раз, а не на каждое слово делать компиляцию

2024-12-24 19:39 UTC, vladislavmass commented on hw03_frequency_analysis/top.go
> +	return keys[:limit]
В данном случае стоит учитывать что данная операция изменит лишь свойство len, но при это весь список слов останется на месте. И условно говоря если у нас 15 слов из которых мы сделали топ 10 и 5 таскаем с собой то это ок, а вот готовы ли мы таскать 10-20к слов ради 10 слов? ( это чисто на подумать. Править не обязательно)

2024-12-26 15:54 UTC, vladislavmass approved these changes

2024-12-26 15:54 UTC, vladislavmass commented on hw03_frequency_analysis/go.mod
> +module github.com/AndreyNagorskiy/hw03_frequency_analysis
В имени модуля все еще есть ошибка

2024-12-26 16:03 UTC, AndreyNagorskiy commented on hw03_frequency_analysis/go.mod
> +module github.com/AndreyNagorskiy/hw03_frequency_analysis
Упс, исправил

2024-12-27 06:15 UTC, merged